[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyxylt"
version = "1.0.0"
description = "XYLT Python package for thesis project"
requires-python = ">=3.8"
